development:
  name: "development"
  email: "solidghost.dev@aol.com"
  role_name: "Admin"

# staging:
#   name: "staging"
#   production: false
#   email: "solidghost.stg@aol.com"
#   role_name: "Admin"

production: 
  name: "production"
  email: "solidghost.prod@aol.com"
  role_name: "Admin"